# Generated by Django 2.2.3 on 2019-07-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190705_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='stored_tweet_string',
            field=models.TextField(null=True),
        ),
    ]
