# Generated by Django 2.2.3 on 2019-08-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_twitteraccount_stored_tweet_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='twitter_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='uncredible_source',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='uncredible_score',
            field=models.FloatField(null=True),
        ),
    ]
