# Generated by Django 2.2.3 on 2019-08-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190808_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteraccount',
            old_name='uncredible_score',
            new_name='misinfo_score',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='uncredible_source',
        ),
        migrations.AddField(
            model_name='tweet',
            name='misinfo_score',
            field=models.IntegerField(null=True),
        ),
    ]
