# Generated by Django 2.2.3 on 2019-08-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_tweet_misinfo_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='cleaned_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='original_text',
            field=models.TextField(null=True),
        ),
    ]
