# Generated by Django 2.2.3 on 2019-08-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190817_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='severe_toxicity_score',
            field=models.FloatField(null=True),
        ),
    ]
