# Generated by Django 2.2.3 on 2019-08-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_twitteraccount_severe_toxicity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='severe_toxicity_score',
            field=models.FloatField(null=True),
        ),
    ]
