# Generated by Django 2.2.3 on 2019-08-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_tweet_severe_toxicity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='attack_on_commenter_score',
            field=models.FloatField(null=True),
        ),
    ]
